### ISSUE TITLE
Erro ao subir Nota de Corretagem 100% BTG

### ISSUE THREAD

**Issue by Josimar** [MarceloPCF/COIR#2]
O ativo MGLU3 ON ainda não foi cadastrado!"
Na planilha Normais_Dados ou DayTrade_Dados do arquivo COIR.xlsb irá aparecer o código MGLU399
Realize a alteração para o código correto do ativo APENAS nessas planilhas.

C:\Josimar\COIR\coir.py:2231: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  ).agg(
C:\Josimar\COIR\coir.py:2231: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  ).agg(
C:\Josimar\COIR\coir.py:2231: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  ).agg(
C:\Josimar\COIR\coir.py:2231: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  ).agg(
Traceback (most recent call last):
  File "C:\Josimar\COIR\coir.py", line 4577, in <module>
    principal()
  File "C:\Josimar\COIR\coir.py", line 4574, in principal
    extracao_nota_corretagem()
  File "C:\Josimar\COIR\coir.py", line 4530, in extracao_nota_corretagem
    btg(corretora,filename,item,log,'all',control=1)
  File "C:\Josimar\COIR\coir.py", line 3686, in btg
    arquivo_unico(current_path,cpf,note_df,normal_df,daytrade_df,taxas_df)
  File "C:\Josimar\COIR\coir.py", line 2646, in arquivo_unico
    writer.book = book
    ^^^^^^^^^^^

MGLU3 ON => Eu coloquei no código para achar o Ticket
MGLU399   => Esse 99 é bizarro
FutureWarning => Sem problemas
COIR.xlsb é copiado sem dados preenchidos

**Comment by Josimar** [comment]
/Resultado / Completo.xlsx => aparece como corrompido

**Comment by MarceloPCF** [comment]
Veja quais as versões estão instaladas em seu computador dos pacotes python:
openpyxl>=3.0.9
pandas>=1.3.3
tabula-py>=2.3.0
xlwings>=0.24.9

Aqui está funcionando com essas versões.

Os arquivos completo.xlsx e COIR.xlsb serão copiados no início do processamento para a pasta resultado, mas os dados só serão inseridos após o processamento pelo script python.

Você por acaso fechou o excel antes de iniciar o processamento?

Subi uma nova versão do coir.py para corrigir o problema do ticket MGLU3.

Esse 99 que inseri ao final do ticket não localizado pelo script é exatamente para chamar a atenção do usuário para as correções necessárias, mostra essa informação tanto na tela quanto no arquivo de log. Mas podemos alterar para algo mais amigável, caso vc tenha uma outra sugestão, esse é exatamente o objetivo de colocar aqui no github. :)

**Comment by MarceloPCF** [comment]
Consegui replicar o erro. 
É a versão do pandas. Se você fizer um downgrade para a versão 1.3.3 vai funcionar.

**Comment by Josimar** [comment]
Vou setar todas as versões que você está usando.

**Comment by MarceloPCF** [comment]
Na realidade tudo que está travado é porque não precisa alterar, caso você coloque notas de anos anteriores todas as planilhas serão alteradas automaticamente para iniciar no primeiro ano de inclusão dos dados.

**Comment by MarceloPCF** [comment]
Fiz a inclusão de arquivo .txt com os pacotes e versões necessários para rodar o coir.py. Inclui também a linha de comando para instalação.
